/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import static Vista.TipDocumentos.jTextDoc_Codigo;
import static Pantallas.principal.escritorio;
import clases.LimitarCaracteres;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class Buscar extends javax.swing.JInternalFrame {
    public static String origen;
    private boolean SinRegistros = false;
        
    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        Limitar();
        
        //System.out.println(origen);
    }
    
    public void Limitar(){
        if (origen=="DOC" || origen=="UND"){
            jTxtBuscaCodigo.setDocument(new LimitarCaracteres(jTxtBuscaCodigo, 3));
        }
        if (origen=="CONT"){
            jTxtBuscaCodigo.setDocument(new LimitarCaracteres(jTxtBuscaCodigo,10));
        }
        if (origen=="PRO"){
            jTxtBuscaCodigo.setDocument(new LimitarCaracteres(jTxtBuscaCodigo,15));
        }
        if (origen=="MON"){
            jTxtBuscaCodigo.setDocument(new LimitarCaracteres(jTxtBuscaCodigo, 6));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtBuscaCodigo = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Codigo");

        jTxtBuscaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtBuscaCodigoKeyPressed(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });
        jBtnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnBuscarKeyPressed(evt);
            }
        });

        jBtnSalir.setText("Cancelar");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtBuscaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBuscar)
                    .addComponent(jBtnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        action_bt_buscar();
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        //this.origen ="";
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jTxtBuscaCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBuscaCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           if (!jTxtBuscaCodigo.getText().trim().isEmpty()){
               jBtnBuscar.requestFocus();
           } 
        }
    }//GEN-LAST:event_jTxtBuscaCodigoKeyPressed

    private void jBtnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnBuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            action_bt_buscar();
        }
    }//GEN-LAST:event_jBtnBuscarKeyPressed

    private void action_bt_buscar(){
        Pantallas.Listas Listar = new Pantallas.Listas();
        String codigo = "";
        
        if (jTxtBuscaCodigo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingrese un codigo para la busqueda");
            return;
        }
        
        if (origen=="DOC"){
            Listar.titulo("Lista de Documentos","Lista de Documentos");
            codigo = jTxtBuscaCodigo.getText();
            
            String sqlCodigo  = "SELECT DOC_CODIGO AS DATO1 FROM DNDOCUMENTOS WHERE DOC_CODIGO='"+codigo+"'";
            String sqlDescrip = "SELECT DOC_DESCRI AS DATO1 FROM DNDOCUMENTOS WHERE DOC_CODIGO='"+codigo+"'";

            this.SinRegistros = Listar.CargaListas(sqlCodigo,sqlDescrip);

            if (this.SinRegistros==true){
                JOptionPane.showMessageDialog(null,"No hay Documentos para listar dentro de las especificaciones indicadas.");
            
            }else{
                Dimension desktopSize = escritorio.getSize();
                Dimension jInternalFrameSize = Listar.getSize();
                Listar.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        
                Listar.show();
                Listas.Tabla="DNDOCUMENTOS";
                Listar.setVisible(true);                
            }
        }
        
        if (origen=="CONT"){
            Listar.titulo("Lista de Tipos de Contactos","Lista de Tipos de Contactos");
            codigo = jTxtBuscaCodigo.getText();
            
            String sqlCodigo  = "SELECT TCON_CODIGO AS DATO1 FROM DNCONTACTOS WHERE TCON_CODIGO='"+codigo+"'";
            String sqlDescrip = "SELECT TCON_DESCRI AS DATO1 FROM DNCONTACTOS WHERE TCON_CODIGO='"+codigo+"'";

            this.SinRegistros = Listar.CargaListas(sqlCodigo,sqlDescrip);

            if (this.SinRegistros==true){
                JOptionPane.showMessageDialog(null,"No hay Contactos para listar dentro de las especificaciones indicadas.");
            
            }else{
                Dimension desktopSize = escritorio.getSize();
                Dimension jInternalFrameSize = Listar.getSize();
                Listar.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
                
                Listar.show();
                Listas.Tabla="DNTIPCONTACTO";
                Listar.setVisible(true);
                
            }
        }
        
        if (origen=="PRO"){
            Listar.titulo("Lista de Productos","Lista de Productos");
            codigo = jTxtBuscaCodigo.getText();
            
            String sqlCodigo  = "SELECT PRO_CODIGO AS DATO1 FROM DNPRODUCTO WHERE PRO_CODIGO='"+codigo+"'";
            String sqlDescrip = "SELECT PRO_DESCRI AS DATO1 FROM DNPRODUCTO WHERE PRO_CODIGO='"+codigo+"'";

            this.SinRegistros = Listar.CargaListas(sqlCodigo,sqlDescrip);

            if (this.SinRegistros==true){
                JOptionPane.showMessageDialog(null,"No hay Productos para listar dentro de las especificaciones indicadas.");
            
            }else{
                Dimension desktopSize = escritorio.getSize();
                Dimension jInternalFrameSize = Listar.getSize();
                Listar.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
                
                Listar.show();
                Listas.Tabla="DNPRODUCT";
                Listar.setVisible(true);
            }
        }
        
        if (origen=="UND"){
            Listar.titulo("Lista de Unidades de Medida","Lista de Unidades de Medida");
            codigo = jTxtBuscaCodigo.getText();
            
            String sqlCodigo  = "SELECT MED_CODIGO AS DATO1 FROM DNUNDMEDIDA WHERE MED_CODIGO='"+codigo+"'";
            String sqlDescrip = "SELECT MED_DESCRI AS DATO1 FROM DNUNDMEDIDA WHERE MED_CODIGO='"+codigo+"'";

            this.SinRegistros = Listar.CargaListas(sqlCodigo,sqlDescrip);

            if (this.SinRegistros==true){
                JOptionPane.showMessageDialog(null,"No hay Unidades de Medidas para listar dentro de las especificaciones indicadas.");
            
            }else{
                Dimension desktopSize = escritorio.getSize();
                Dimension jInternalFrameSize = Listar.getSize();
                Listar.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
                
                Listar.show();
                Listas.Tabla="DNUNDMED";
                Listar.setVisible(true);
            }
        }
        
        if (origen=="MON"){
            Listar.titulo("Lista de Monedas","Lista de Monedas");
            codigo = jTxtBuscaCodigo.getText();
            
            String sqlCodigo  = "SELECT MON_CODIGO AS DATO1 FROM DNMONEDA WHERE MON_CODIGO='"+codigo+"'";
            String sqlDescrip = "SELECT MON_NOMBRE AS DATO1 FROM DNMONEDA WHERE MON_CODIGO='"+codigo+"'";

            this.SinRegistros = Listar.CargaListas(sqlCodigo,sqlDescrip);

            if (this.SinRegistros==true){
                JOptionPane.showMessageDialog(null,"No hay Monedas para listar dentro de las especificaciones indicadas.");
            
            }else{
                Dimension desktopSize = escritorio.getSize();
                Dimension jInternalFrameSize = Listar.getSize();
                Listar.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
                
                Listar.show();
                Listas.Tabla="DNMONE";
                Listar.setVisible(true);
            }
        }
        
        
        
        //this.origen ="";
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtBuscaCodigo;
    // End of variables declaration//GEN-END:variables
}