/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pantallas;

import clases.SQLQuerys;
import clases.SQLSelect;
import clases.CargaTablas;
import clases.CodigoConsecutivo;
import clases.LimitarCaracteres;
import clases.ValidaCodigo;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.OptionPaneUI;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.utils.SubstanceConstants;
import org.jvnet.substance.watermark.SubstanceImageWatermark;

/**
 *
 * @author Kelvin Marcano
 */
public class PlanCuentas extends javax.swing.JInternalFrame {
      CargaTablas cargatabla = null;
    private SQLSelect Registros;

    

    /**
     * Creates new form PlanCuentas
     */
    public PlanCuentas() {
        initComponents();
        
         Limitar();
    }
    
     public void Limitar(){
                jTxtCta_Codest.setDocument(new LimitarCaracteres(jTxtCta_Codest, 6));
                jTxtCta_Tipcta.setDocument(new LimitarCaracteres(jTxtCta_Tipcta, 6));
                jTxtCta_Cuenta.setDocument(new LimitarCaracteres(jTxtCta_Cuenta, 50));
                jTxtCta_Titulo.setDocument(new LimitarCaracteres(jTxtCta_Titulo, 50));
//                jTxtCta_Descri.setDocument(new LimitarCaracteres(jTxtCta_Descri, 100));
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAgregar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabPlanCta = new javax.swing.JTable();
        jBtnAdelante = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();
        jBtnAnterior = new javax.swing.JButton();
        Datos_PlanCuenta = new javax.swing.JPanel();
        jLabCta_Codest = new javax.swing.JLabel();
        jTxtCta_Codest = new javax.swing.JTextField();
        jLabCta_Tipcta = new javax.swing.JLabel();
        jTxtCta_Tipcta = new javax.swing.JTextField();
        jLabCta_Cuenta = new javax.swing.JLabel();
        jTxtCta_Cuenta = new javax.swing.JTextField();
        jLabCta_Titulo = new javax.swing.JLabel();
        jTxtCta_Titulo = new javax.swing.JTextField();
        jLabCta_Tipsal = new javax.swing.JLabel();
        jCmbCta_Tipsal = new javax.swing.JComboBox();
        jLabCta_Descri = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtCta_Descri = new javax.swing.JTextArea();
        jLabCta_Perten = new javax.swing.JLabel();
        jCmbCta_Perten = new javax.swing.JComboBox();
        jLabCta_Tipo = new javax.swing.JLabel();
        jCmbCta_Tipo = new javax.swing.JComboBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnAgregar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964960_Add.png"))); // NOI18N
        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 70, 120, 40));

        jBtnEliminar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964909_Erase.png"))); // NOI18N
        jBtnEliminar.setText("Eliminar");
        getContentPane().add(jBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 120, 40));

        jBtnSalir.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964916_Exit.png"))); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 120, 30));

        jBtnEditar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964940_Pencil.png"))); // NOI18N
        jBtnEditar.setText("Modificar");
        getContentPane().add(jBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 120, 40));

        jTabPlanCta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Título", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabPlanCta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 770, 170));

        jBtnAdelante.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964902_Forward.png"))); // NOI18N
        jBtnAdelante.setText("Adelante");
        getContentPane().add(jBtnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 120, 40));

        jBtnBuscar.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964921_Find.png"))); // NOI18N
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 120, 40));

        jBtnAnterior.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jBtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1409964894_Back.png"))); // NOI18N
        jBtnAnterior.setText("Anterior");
        getContentPane().add(jBtnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 120, 40));

        Datos_PlanCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        Datos_PlanCuenta.setToolTipText("");
        Datos_PlanCuenta.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N

        jLabCta_Codest.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Codest.setText("Estructura:");

        jTxtCta_Codest.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jTxtCta_Codest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCta_CodestFocusLost(evt);
            }
        });

        jLabCta_Tipcta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Tipcta.setText("Tipo de Cuenta:");

        jTxtCta_Tipcta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jTxtCta_Tipcta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCta_TipctaFocusLost(evt);
            }
        });

        jLabCta_Cuenta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Cuenta.setText("Cuenta:");

        jTxtCta_Cuenta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jTxtCta_Cuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCta_CuentaFocusLost(evt);
            }
        });

        jLabCta_Titulo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Titulo.setText("Título:");

        jTxtCta_Titulo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jTxtCta_Titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCta_TituloFocusLost(evt);
            }
        });

        jLabCta_Tipsal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Tipsal.setText("Saldo:");

        jCmbCta_Tipsal.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jCmbCta_Tipsal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deudor", "Acreedor" }));
        jCmbCta_Tipsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCta_TipsalActionPerformed(evt);
            }
        });

        jLabCta_Descri.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Descri.setText("Descripción:");

        jTxtCta_Descri.setColumns(20);
        jTxtCta_Descri.setRows(5);
        jScrollPane3.setViewportView(jTxtCta_Descri);

        jLabCta_Perten.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Perten.setText("Pertenece a:");

        jCmbCta_Perten.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jCmbCta_Perten.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Real", "Nominal" }));
        jCmbCta_Perten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCta_PertenActionPerformed(evt);
            }
        });

        jLabCta_Tipo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabCta_Tipo.setText("Tipo:");

        jCmbCta_Tipo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jCmbCta_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monetaria", "No monetaria" }));
        jCmbCta_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCta_TipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Datos_PlanCuentaLayout = new javax.swing.GroupLayout(Datos_PlanCuenta);
        Datos_PlanCuenta.setLayout(Datos_PlanCuentaLayout);
        Datos_PlanCuentaLayout.setHorizontalGroup(
            Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                        .addComponent(jLabCta_Codest, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCta_Codest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabCta_Tipcta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCta_Tipcta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabCta_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCta_Cuenta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Datos_PlanCuentaLayout.createSequentialGroup()
                        .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Datos_PlanCuentaLayout.createSequentialGroup()
                                .addComponent(jLabCta_Descri, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Datos_PlanCuentaLayout.createSequentialGroup()
                                .addComponent(jLabCta_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtCta_Titulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                                .addComponent(jLabCta_Tipsal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCmbCta_Tipsal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                                .addComponent(jLabCta_Perten, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCmbCta_Perten, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                                .addComponent(jLabCta_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCmbCta_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        Datos_PlanCuentaLayout.setVerticalGroup(
            Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabCta_Codest)
                    .addComponent(jTxtCta_Codest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCta_Tipcta)
                    .addComponent(jTxtCta_Tipcta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCta_Cuenta)
                    .addComponent(jTxtCta_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabCta_Titulo)
                    .addComponent(jTxtCta_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCta_Tipsal)
                    .addComponent(jCmbCta_Tipsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCta_Descri)
                    .addGroup(Datos_PlanCuentaLayout.createSequentialGroup()
                        .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCta_Perten)
                            .addComponent(jCmbCta_Perten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Datos_PlanCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabCta_Tipo)
                            .addComponent(jCmbCta_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(270, 270, 270))
        );

        getContentPane().add(Datos_PlanCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        String valor = null;
        String codest = null;
        String tipcta = null;
        String cuenta = null;
        String titulo = null;
        String  descri = null;
        String tipsal = null;
        String Perten = null;
        String Tipo = null;

        if ("".equals(jTxtCta_Codest.getText())){
            JOptionPane.showMessageDialog(null,"Debe Ingresar el Código del Catálogo");
            jTxtCta_Codest.requestFocus();
            return;
        }

        if ("".equals(jTxtCta_Tipcta.getText())){
            JOptionPane.showMessageDialog(null,"Debe Ingresar el Tipo de Cuenta");
            jTxtCta_Tipcta.requestFocus();
            return;
        }

        if ("".equals(jTxtCta_Cuenta.getText())){
            JOptionPane.showMessageDialog(null,"Debe Ingresar la Cuenta");
            jTxtCta_Cuenta.requestFocus();
            return;
        }

        if ("".equals(jTxtCta_Titulo.getText())){
            JOptionPane.showMessageDialog(null,"Debe Ingresar el Título");
            jTxtCta_Titulo.requestFocus();
            return;
        }

        if ("".equals(jTxtCta_Descri.getText())){
            JOptionPane.showMessageDialog(null,"Debe Ingresar la Descripción");
            jTxtCta_Descri.requestFocus();
            return;
        }

        DefaultTableModel model = (DefaultTableModel) this.jTabPlanCta.getModel();
        String [] filas={jTxtCta_Cuenta.getText(),jTxtCta_Titulo.getText(),jCmbCta_Tipsal.getSelectedItem().toString()};
        model.addRow(filas);

        codest = jTxtCta_Codest.getText();
        tipcta = jTxtCta_Tipcta.getText();
        cuenta = jTxtCta_Cuenta.getText();
        titulo = jTxtCta_Titulo.getText();
        descri = jTxtCta_Descri.getText();
        tipsal = jCmbCta_Tipsal.getSelectedItem().toString();

        jTxtCta_Codest.setText("");
        jTxtCta_Tipcta.setText("");
        jTxtCta_Cuenta.setText("");
        jTxtCta_Titulo.setText("");
        jTxtCta_Descri.setText("");

        SQLQuerys insertar = new SQLQuerys();

        insertar.SqlInsert("INSERT INTO DNPLANCTA SET CTA_CODEST='"+codest+"', "+
            "CTA_TIPCTA='"+tipcta+"',"+
            "CTA_CUENTA='"+cuenta+"',"+
            "CTA_TITULO='"+titulo+"',"+
            "CTA_DESCRI='"+descri+"',"+
            "CTA_TIPSAL='"+tipsal.substring(0, 1)+"', "+
            "CTA_PERTEN='"+Perten+"', "+
            "CTA_TIPO='"+Tipo+"'"
        );
        JOptionPane.showMessageDialog(null, "ssss");
        jTxtCta_Codest.requestFocus();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jTxtCta_CodestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCta_CodestFocusLost
        // TODO add your handling code here:
        if (!"".equals(jTxtCta_Codest.getText())){
            cargatabla = new CargaTablas();
            String SQL = "SELECT CTA_CUENTA, CTA_TITULO, IF(CTA_TIPSAL='D','Deudor','Acreedor') AS CTA_TIPSAL FROM DNPLANCTA "+
            "WHERE CTA_CODEST='"+jTxtCta_Codest.getText()+"'  "+
            "ORDER BY CTA_CUENTA";
            String[] columnas = {"Cuenta","Título","Saldo"};

            cargatabla.cargatablas(jTabPlanCta, SQL, columnas);
            jTabPlanCta.getColumn("Cuenta").setWidth(10);   //no esta funcionando ***** DL
        }
    }//GEN-LAST:event_jTxtCta_CodestFocusLost

    private void jTxtCta_TipctaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCta_TipctaFocusLost
        // TODO add your handling code here:
        if (!"".equals(jTxtCta_Codest.getText()) && !"".equals(jTxtCta_Tipcta.getText())){
            cargatabla = new CargaTablas();
            String SQL = "SELECT CTA_CUENTA, CTA_TITULO, IF(CTA_TIPSAL='D','Deudor','Acreedor') AS CTA_TIPSAL FROM DNPLANCTA "+
            "WHERE CTA_CODEST='"+jTxtCta_Codest.getText()+"'  AND CTA_TIPCTA='"+jTxtCta_Tipcta.getText()+"' "+
            "ORDER BY CTA_CUENTA";
            String[] columnas = {"Cuenta","Título","Saldo"};

            cargatabla.cargatablas(jTabPlanCta,SQL,columnas);
            jTabPlanCta.getColumn("Cuenta").setWidth(10);   //no esta funcionando ***** DL
        }
    }//GEN-LAST:event_jTxtCta_TipctaFocusLost

    private void jTxtCta_CuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCta_CuentaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCta_CuentaFocusLost

    private void jTxtCta_TituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCta_TituloFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCta_TituloFocusLost

    private void jCmbCta_TipsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCta_TipsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCta_TipsalActionPerformed

    private void jCmbCta_PertenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCta_PertenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCta_PertenActionPerformed

    private void jCmbCta_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCta_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbCta_TipoActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datos_PlanCuenta;
    private javax.swing.JButton jBtnAdelante;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnAnterior;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox jCmbCta_Perten;
    private javax.swing.JComboBox jCmbCta_Tipo;
    private javax.swing.JComboBox jCmbCta_Tipsal;
    private javax.swing.JLabel jLabCta_Codest;
    private javax.swing.JLabel jLabCta_Cuenta;
    private javax.swing.JLabel jLabCta_Descri;
    private javax.swing.JLabel jLabCta_Perten;
    private javax.swing.JLabel jLabCta_Tipcta;
    private javax.swing.JLabel jLabCta_Tipo;
    private javax.swing.JLabel jLabCta_Tipsal;
    private javax.swing.JLabel jLabCta_Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabPlanCta;
    private javax.swing.JTextField jTxtCta_Codest;
    private javax.swing.JTextField jTxtCta_Cuenta;
    private javax.swing.JTextArea jTxtCta_Descri;
    private javax.swing.JTextField jTxtCta_Tipcta;
    private javax.swing.JTextField jTxtCta_Titulo;
    // End of variables declaration//GEN-END:variables
}
