SELECT ENC_CODIGO, ENC_CODDOC, INV_CODPRO,PRO_DESCRI,INV_CANTID,ENC_BASE,ENC_IVA,
ENC_MONTO,MAE_CODIGO,MAE_NOMBRE,MAE_RIF,MAE_EMAIL FROM dnencabezado
LEFT JOIN dninventario ON INV_CODPRO=ENC_CODIGO
LEFT JOIN dnproducto ON PRO_CODIGO=INV_CODPRO
LEFT JOIN dnprecio ON PRE_CODIGO=PRO_CODIGO
INNER JOIN dnmaestro ON MAE_CODIGO=ENC_CODMAE
WHERE ENC_CODIGO=$P{numfact}